name: CI

on: [push]

jobs:
  test:
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1 # https://github.com/ruby/setup-ruby
        with:
          bundler-cache: true # https://github.com/ruby/setup-ruby#dealing-with-a-corrupted-cache
      - name: Install Gems
        run: gem install bundler && bundle install --jobs 4 --retry 3
      - name: Build and test with Rake
        run: |
          bundle exec rspec
