name: CI

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [2.7, 3.1, 3.2]
    runs-on:  ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # https://github.com/ruby/setup-ruby#dealing-with-a-corrupted-cache
      - name: Install Gems
        run: gem install bundler && bundle install --jobs 4 --retry 3
      - name: Build and test with Rake
        run: |
          bundle exec rspec
